In [1]:
import numpy as np 

In [10]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [22]:
c = b.ndim # Get Dimension (kích thước của mảng)
z = a.ndim
print(z)
print(c)

1
2


In [21]:
c = b.shape #Get shape(hình dáng của mảng)
z = a.shape
print(z)
print(c)

(2, 3)
(3,)


In [12]:
a.dtype #get type

dtype('int16')

In [18]:
#Get size
z = a.itemsize
c = b.itemsize
print(z)
print(c)

2
8


In [20]:
#Get total size
z = a.nbytes
c = b.nbytes
print(z)
print(c)

6
48


In [23]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
# Get a specific alement[r, c] tìm vị trí của giá trị trong mảng 
a[1,5]

13

In [32]:
# Get a specifiv row
z = a[0, :]
c = a[1, :]

print(z)
print(c)

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [34]:
# Get a specific column

a[:, 2]

array([ 3, 10])

In [35]:
# Getting a little more fancy [ startindex: endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [41]:
a[1,6] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 20]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 20]]


In [42]:
*3-d exmaple


SyntaxError: invalid syntax (1623184793.py, line 1)

In [43]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
# Get specifc element (work outside in)
b[0,1,1]

4

In [45]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [46]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [47]:
# ALL 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
# ALL is matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [50]:
np.full((2,2), 99) # Any other number

array([[99, 99],
       [99, 99]])

In [51]:
# Any other number (full_like) new array theo yêu cầu 

np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [64]:
# Random decimal numbers
z = np.random.rand(4,2)
c = np.random.rand(4,2,3)

print(z)
print('\n')
print(c)

[[0.34247086 0.97658144]
 [0.17528642 0.62128743]
 [0.93875052 0.52408124]
 [0.20442773 0.69754677]]


[[[0.35953427 0.29087842 0.10046541]
  [0.79444982 0.68006718 0.67192716]]

 [[0.63669189 0.15574827 0.49199978]
  [0.70100306 0.96658375 0.22790272]]

 [[0.57156373 0.69152712 0.5088914 ]
  [0.15695891 0.34769486 0.74010112]]

 [[0.22676026 0.95103198 0.69122967]
  [0.92790292 0.09779182 0.29014408]]]


In [92]:
# Random Integer values
np.random.randint(4,7, size=(3,3))

array([[5, 5, 6],
       [5, 5, 5],
       [6, 5, 5]])

In [93]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [94]:
# repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [95]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z 
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


####
Be careful when copying arrays

In [100]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100 

print(a)

[1 2 3]


Mathmatics


In [101]:
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [102]:
a + 2

array([3, 4, 5, 6])

In [103]:
a - 2

array([-1,  0,  1,  2])

In [104]:
a * 2

array([2, 4, 6, 8])

In [105]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [106]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [107]:
a ** 2 # (**) mũ 

array([ 1,  4,  9, 16])

In [112]:
# Take the sin
z = np.sin(a)
c = np.cos(a)

print(z)
print('\n')
print(c)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


Linear Algebra

In [116]:
a = np.ones((2,3))
print(a)
print('\n')
b = np.full((3,2),2)
print(b)

np.matmul(a,b) # nhân ma trận cùng dạng 

[[1. 1. 1.]
 [1. 1. 1.]]


[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [117]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c) # tính định thức (chỉ có trong ma trận vuông)  

1.0

#### Statistics


In [118]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
np.min(stats)

1

In [121]:
np.max(stats, axis = 1)

array([3, 6])

In [122]:
np.sum(stats, axis = 0)

array([5, 7, 9])

#### Reorganizing Arrays


In [126]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print('\n')
after = before.reshape((4,2)) # thay đổi kích thước của mảng
print(after)

[[1 2 3 4]
 [5 6 7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [127]:
# vertically stacking vecotrs (chồng mảng với mảng theo chiều dọc)
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [151]:
# Horizontal stack (chồng mảng với mảng theo chiều ngang)
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous 

Load Data from File

In [152]:
data = np.genfromtxt('/Users/sinhtran/Desktop/data.txt', delimiter=',')
data.astype('int32')
print(data)
data

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  75.  88.]]


array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  75.,  88.]])

In [153]:
data[data > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  75.,  88.])

#### Boolean Masking and Advanced indexing



In [154]:
np.all(data > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [155]:
(~((data > 50) & (data < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [157]:
np.dot(data)

TypeError: dot() missing 1 required positional argument: 'b'

In [158]:
import numpy as np

# Creating two 1-D arrays
a = np.array([2, 3])
b = np.array([4, 5])

# Calculating the dot product
result = np.dot(a, b) #nhân hai vector

# Displaying the result
print(result)


23
